version: "3.8"
name: aims

services:
  profile-db:
    image: mongo:latest
    container_name: profile_db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=aims
      - MONGO_INITDB_ROOT_PASSWORD=aims
      - MONGO_INITDB_DATABASE=profiles
    ports:
      - "27019:27017"
    volumes:
      - profile_db_data:/data/db
      - profile_db_config:/data/configdb

  profile-ms:
    build: .
    image: aims_profile_ms
    container_name: profile_ms
    environment:
      - MONGO_URI=mongodb://aims:aims@profile-db:27017/profiles?authSource=admin
    ports:
      - "4000:4000"
    depends_on:
      - profile-db
    links:
      - profile-db

volumes:
  profile_db_data:
  profile_db_config:
