@baseUrl=http://localhost:4000

@userId={{newProfile.request.body.user_id}}


### Create profile
# @name newProfile
POST {{baseUrl}}/profiles HTTP/1.1
Content-Type: application/json

{
  "user_id": "{{$guid}}",
  "name": "John",
  "lastname": "Doe",
  "email": "johndoe@gmail.com",
  "birthdate": "15/01/1990",
  "phone_number": "1234567890",
  "address": "1234 Main St",
  "historials": [
    {
        "career": "Computer Science",
        "GPA": "3.5",
        "coursed_credits": 120,
        "approved_credits": 80,
        "reprobed_credits": 10,
        "enrollment_id": 1
    }
  ]
}

### Get profile
# @name getProfile
GET {{baseUrl}}/profiles/{{userId}} HTTP/1.1

### Get all profiles
# @name getAllProfiles
GET {{baseUrl}}/profiles HTTP/1.1

### Update profile
# @name updateProfile
PUT {{baseUrl}}/profiles/{{userId}} HTTP/1.1
Content-Type: application/json

{
  "user_id": "{{userId}}",
  "name": "John",
  "lastname": "Doe",
  "email": "johndoe@gmail.com",
  "birthdate": "15/01/1990",
  "phone_number": "1234567890",
  "address": "1234 Main St",
  "historials": [
    {
      "career": "Computer Science",
      "GPA": "4",
      "coursed_credits": 120,
      "approved_credits": 90,
      "reprobed_credits": 10,
      "enrollment_id": 1
    }
  ]
}

### Delete profile
# @name deleteProfile
DELETE {{baseUrl}}/profiles/{{userId}} HTTP/1.1

